##### WAS Part ##### 
FROM node:lts

# 작업 디렉터리 설정
WORKDIR /usr/src/app/

# package.json 및 package-lock.json 파일 복사 및 의존성 설치
COPY ./package*.json ./
RUN npm install --silent   
RUN npm install -g nodemon

# 소스 코드 복사
COPY . .

##### RUN Part #####
CMD ["npm", "start"]

# 서버 부담 줄이기 위해 --silent
# nodemon 오류 원천 봉쇄 위해 전역 설치
